//
//  NamesOfAllahData.swift
//  shukr
//
//  Allah and the 99 Names, in the order of the Tirmidhi list. Transliteration, meanings and
//  explanations come from the owner's 99Duas project (github.com/izhansari/99Duas,
//  `duas_99_names.jsx`, the `D` array); the Arabic is the standard spelling with full tashkeel,
//  added here — without the vowel marks the Uthmani font reads like stock Arabic type. The
//  owner's personal duas and their life-area categories are deliberately not included — every
//  user gets their own later through the AI-dua feature (CLAUDE.md, "99 Names").
//

import Foundation

struct AllahName: Identifiable, Hashable {
    let id: Int            // 0 = Allah, 1…99
    let transliteration: String
    let arabic: String
    let meaning: String
    let alsoMeans: String
    let explanation: String
}

enum NamesOfAllah {
    static let all: [AllahName] = [
        AllahName(id: 0, transliteration: "Allah", arabic: "اللَّهُ", meaning: "God", alsoMeans: "The Deity, The One Worthy of Worship",
                  explanation: "The greatest Name encompassing all attributes — the one and only deity worthy of worship."),
        AllahName(id: 1, transliteration: "Ar-Rahman", arabic: "الرَّحْمَٰنُ", meaning: "The All-Compassionate", alsoMeans: "The Most Gracious, The Beneficent",
                  explanation: "His mercy is vast and universal — extending to every creature. The womb (rahim) derives from the same root."),
        AllahName(id: 2, transliteration: "Ar-Raheem", arabic: "الرَّحِيمُ", meaning: "The Most Merciful", alsoMeans: "The Most Merciful, The Compassionate",
                  explanation: "His special, intimate mercy reserved for believers — guiding back when you stray, softening hearts."),
        AllahName(id: 3, transliteration: "Al-Malik", arabic: "الْمَلِكُ", meaning: "The King", alsoMeans: "The Sovereign, The Master",
                  explanation: "The absolute ruler whose sovereignty is total and eternal. Everything you possess belongs to Him."),
        AllahName(id: 4, transliteration: "Al-Quddus", arabic: "الْقُدُّوسُ", meaning: "The Most Holy", alsoMeans: "The Most Pure, The Sacred",
                  explanation: "Absolutely pure — free from every flaw. Only the Pure can purify."),
        AllahName(id: 5, transliteration: "As-Salam", arabic: "السَّلَامُ", meaning: "The Source of Peace", alsoMeans: "The Giver of Peace, The Flawless",
                  explanation: "The origin of all peace and security. Peace is found in proximity to Him."),
        AllahName(id: 6, transliteration: "Al-Mu'min", arabic: "الْمُؤْمِنُ", meaning: "The Inspirer of Faith", alsoMeans: "The Guardian of Faith, The Faithful",
                  explanation: "He grants security, confirms truth, and inspires faith."),
        AllahName(id: 7, transliteration: "Al-Muhaymin", arabic: "الْمُهَيْمِنُ", meaning: "The Guardian", alsoMeans: "The Protector, The Overseer",
                  explanation: "He watches over all things with complete authority. Nothing escapes His care."),
        AllahName(id: 8, transliteration: "Al-Aziz", arabic: "الْعَزِيزُ", meaning: "The Almighty", alsoMeans: "The Exalted in Might, The Invincible",
                  explanation: "All might paired with wisdom. Every empire that oppressed crumbled before Him."),
        AllahName(id: 9, transliteration: "Al-Jabbar", arabic: "الْجَبَّارُ", meaning: "The Restorer", alsoMeans: "The Compeller, The Repairer of the Broken",
                  explanation: "He compels creation to His will and mends what is broken. 'Jabr' means to set a broken bone."),
        AllahName(id: 10, transliteration: "Al-Mutakabbir", arabic: "الْمُتَكَبِّرُ", meaning: "The Supreme", alsoMeans: "The Greatest, The Most Majestic",
                  explanation: "All greatness belongs exclusively to Him. Pride is His garment alone."),
        AllahName(id: 11, transliteration: "Al-Khaliq", arabic: "الْخَالِقُ", meaning: "The Creator", alsoMeans: "The Maker of All, The Planner",
                  explanation: "He brought everything from nothing. Your ability to create is borrowed light."),
        AllahName(id: 12, transliteration: "Al-Bari'", arabic: "الْبَارِئُ", meaning: "The Originator", alsoMeans: "The Evolver, The Maker of Order",
                  explanation: "He creates all beings with distinct form, free from prior model."),
        AllahName(id: 13, transliteration: "Al-Musawwir", arabic: "الْمُصَوِّرُ", meaning: "The Fashioner", alsoMeans: "The Shaper of Beauty, The Fashioner",
                  explanation: "The divine Designer. Your eye for beauty traces back to Him."),
        AllahName(id: 14, transliteration: "Al-Ghaffar", arabic: "الْغَفَّارُ", meaning: "The Repeatedly Forgiving", alsoMeans: "The Ever-Forgiving, The Veiler of Sins",
                  explanation: "He forgives again and again with no limit. The door is never locked."),
        AllahName(id: 15, transliteration: "Al-Qahhar", arabic: "الْقَهَّارُ", meaning: "The Subduer", alsoMeans: "The Crusher, The Irresistible",
                  explanation: "He prevails with irresistible power. Every tyrant is subdued before Him."),
        AllahName(id: 16, transliteration: "Al-Wahhab", arabic: "الْوَهَّابُ", meaning: "The Bestower", alsoMeans: "The Liberal Bestower, The Giver of Gifts",
                  explanation: "He gives abundantly, freely, without expecting return."),
        AllahName(id: 17, transliteration: "Ar-Razzaq", arabic: "الرَّزَّاقُ", meaning: "The Provider", alsoMeans: "The Sustainer, The Provider of All",
                  explanation: "The ultimate Provider. He provides before you ask, through doors you didn't knock on."),
        AllahName(id: 18, transliteration: "Al-Fattah", arabic: "الْفَتَّاحُ", meaning: "The Opener", alsoMeans: "The Victory Giver, The Opener of Gates",
                  explanation: "He opens what is closed — doors of mercy, provision, tongues."),
        AllahName(id: 19, transliteration: "Al-'Aleem", arabic: "الْعَلِيمُ", meaning: "The All-Knowing", alsoMeans: "The Omniscient, The All-Knowing",
                  explanation: "His knowledge encompasses everything. Every human ideology is partial before Him."),
        AllahName(id: 20, transliteration: "Al-Qabid", arabic: "الْقَابِضُ", meaning: "The Restrainer", alsoMeans: "The Restrainer, The Withholder",
                  explanation: "He constricts by wisdom. Sometimes tightness is a divine redirect."),
        AllahName(id: 21, transliteration: "Al-Basit", arabic: "الْبَاسِطُ", meaning: "The Expander", alsoMeans: "The Extender, The Reliever",
                  explanation: "He expands provision, hearts, and confidence. Your capacity for expression is not fixed."),
        AllahName(id: 22, transliteration: "Al-Khafid", arabic: "الْخَافِضُ", meaning: "The Humbler", alsoMeans: "The Humiliator, The Abaser",
                  explanation: "He lowers whoever He wills. Ask to be humbled gently in private."),
        AllahName(id: 23, transliteration: "Ar-Rafi'", arabic: "الرَّافِعُ", meaning: "The Exalter", alsoMeans: "The Elevator, The Uplifter",
                  explanation: "He raises in rank and honor. True elevation comes from Him alone."),
        AllahName(id: 24, transliteration: "Al-Mu'izz", arabic: "الْمُعِزُّ", meaning: "The Giver of Honor", alsoMeans: "The Bestower of Honor, The Honorer",
                  explanation: "True honor comes from Allah alone."),
        AllahName(id: 25, transliteration: "Al-Mudhill", arabic: "الْمُذِلُّ", meaning: "Giver of Disgrace", alsoMeans: "The Dishonorer, The One Who Lowers",
                  explanation: "He strips honor from whoever persists in arrogance or hypocrisy."),
        AllahName(id: 26, transliteration: "As-Samee'", arabic: "السَّمِيعُ", meaning: "The All-Hearing", alsoMeans: "The All-Hearing, The Hearer of All",
                  explanation: "He hears every whispered du'a, every cry, every unspoken thought."),
        AllahName(id: 27, transliteration: "Al-Baseer", arabic: "الْبَصِيرُ", meaning: "The All-Seeing", alsoMeans: "The All-Seeing, The Seer of All",
                  explanation: "He sees everything — the tears you cry alone, the sincerity behind the struggle."),
        AllahName(id: 28, transliteration: "Al-Hakam", arabic: "الْحَكَمُ", meaning: "The Judge", alsoMeans: "The Judge, The Arbitrator",
                  explanation: "The ultimate Judge whose verdict is final."),
        AllahName(id: 29, transliteration: "Al-'Adl", arabic: "الْعَدْلُ", meaning: "The Just", alsoMeans: "The Utterly Just, The Equitable",
                  explanation: "Perfect justice. He does not wrong anyone by an atom's weight."),
        AllahName(id: 30, transliteration: "Al-Lateef", arabic: "اللَّطِيفُ", meaning: "The Subtle", alsoMeans: "The Gentle, The Subtle One",
                  explanation: "His kindness reaches you through invisible pathways."),
        AllahName(id: 31, transliteration: "Al-Khabeer", arabic: "الْخَبِيرُ", meaning: "The All-Aware", alsoMeans: "The All-Aware, The Acquainted",
                  explanation: "He knows the inner reality of everything — every hidden motive."),
        AllahName(id: 32, transliteration: "Al-Haleem", arabic: "الْحَلِيمُ", meaning: "The Forbearing", alsoMeans: "The Most Clement, The Forbearing",
                  explanation: "He does not rush to punish. Supreme power restrained by supreme mercy."),
        AllahName(id: 33, transliteration: "Al-'Adheem", arabic: "الْعَظِيمُ", meaning: "The Magnificent", alsoMeans: "The Great One, The Tremendous",
                  explanation: "Incomprehensible greatness. When you feel His greatness, human opinions become very small."),
        AllahName(id: 34, transliteration: "Al-Ghafoor", arabic: "الْغَفُورُ", meaning: "The All-Forgiving", alsoMeans: "The Oft-Forgiving, The Pardoner",
                  explanation: "He covers sins completely. Your past does not define your future."),
        AllahName(id: 35, transliteration: "Ash-Shakoor", arabic: "الشَّكُورُ", meaning: "The Appreciative", alsoMeans: "The Appreciative, The Rewarder",
                  explanation: "He multiplies the smallest good deeds. Nothing is too small."),
        AllahName(id: 36, transliteration: "Al-'Aliyy", arabic: "الْعَلِيُّ", meaning: "The Most High", alsoMeans: "The Highest, The Transcendent",
                  explanation: "Above all creation. Stop placing money or opinions on pedestals."),
        AllahName(id: 37, transliteration: "Al-Kabeer", arabic: "الْكَبِيرُ", meaning: "The Most Great", alsoMeans: "The Most Great, The Supreme",
                  explanation: "He didn't give you ambition just to live on autopilot."),
        AllahName(id: 38, transliteration: "Al-Hafeez", arabic: "الْحَفِيظُ", meaning: "The Preserver", alsoMeans: "The Preserver, The Guardian",
                  explanation: "He is holding it all in place when everything feels fragile."),
        AllahName(id: 39, transliteration: "Al-Muqeet", arabic: "الْمُقِيتُ", meaning: "The Nourisher", alsoMeans: "The Maintainer, The Feeder",
                  explanation: "He nourishes the seed underground before it breaks soil."),
        AllahName(id: 40, transliteration: "Al-Haseeb", arabic: "الْحَسِيبُ", meaning: "The Reckoner", alsoMeans: "The Reckoner, The Sufficient",
                  explanation: "Both accountability and sufficiency."),
        AllahName(id: 41, transliteration: "Al-Jaleel", arabic: "الْجَلِيلُ", meaning: "The Majestic", alsoMeans: "The Sublime, The Majestic One",
                  explanation: "Presence that commands awe without a word."),
        AllahName(id: 42, transliteration: "Al-Kareem", arabic: "الْكَرِيمُ", meaning: "The Most Generous", alsoMeans: "The Noble, The Bountiful",
                  explanation: "He gives before you ask, more than you deserve. He cannot not give."),
        AllahName(id: 43, transliteration: "Ar-Raqeeb", arabic: "الرَّقِيبُ", meaning: "The Watchful", alsoMeans: "The Watchful, The Ever-Observing",
                  explanation: "He watches for accountability through ihsan, not punishment."),
        AllahName(id: 44, transliteration: "Al-Mujeeb", arabic: "الْمُجِيبُ", meaning: "The Responsive", alsoMeans: "The Responsive, The Answerer of Prayer",
                  explanation: "He answers every call — sometimes differently than expected."),
        AllahName(id: 45, transliteration: "Al-Wasi'", arabic: "الْوَاسِعُ", meaning: "The Vast", alsoMeans: "The Vast, The All-Encompassing",
                  explanation: "His provision has no ceiling. What He set aside for you cannot be taken."),
        AllahName(id: 46, transliteration: "Al-Hakeem", arabic: "الْحَكِيمُ", meaning: "The All-Wise", alsoMeans: "The All-Wise, The Perfectly Wise",
                  explanation: "Everything with perfect wisdom. Every delay has a purpose."),
        AllahName(id: 47, transliteration: "Al-Wadud", arabic: "الْوَدُودُ", meaning: "The Most Loving", alsoMeans: "The Most Loving, The Affectionate",
                  explanation: "He loves deeply, actively, personally."),
        AllahName(id: 48, transliteration: "Al-Majeed", arabic: "الْمَجِيدُ", meaning: "The All-Glorious", alsoMeans: "The Most Glorious, The Noble",
                  explanation: "Supreme glory with supreme generosity. The right thing at the right time."),
        AllahName(id: 49, transliteration: "Al-Ba'ith", arabic: "الْبَاعِثُ", meaning: "The Resurrector", alsoMeans: "The Raiser of the Dead, The Awakener",
                  explanation: "He will raise every soul. What will you be raised with?"),
        AllahName(id: 50, transliteration: "Ash-Shaheed", arabic: "الشَّهِيدُ", meaning: "The Witness", alsoMeans: "The Witness, The Ever-Present",
                  explanation: "He witnesses all things. For the one who feels unseen — nothing was wasted."),
        AllahName(id: 51, transliteration: "Al-Haqq", arabic: "الْحَقُّ", meaning: "The Truth", alsoMeans: "The Absolute Truth, The Reality",
                  explanation: "The absolute Truth. Build on truth and it stands forever."),
        AllahName(id: 52, transliteration: "Al-Wakeel", arabic: "الْوَكِيلُ", meaning: "The Trustee", alsoMeans: "The Disposer of Affairs, The Trustee",
                  explanation: "The spreadsheet is yours. The outcome is His."),
        AllahName(id: 53, transliteration: "Al-Qawiyy", arabic: "الْقَوِيُّ", meaning: "The All-Strong", alsoMeans: "The Most Strong, The Powerful",
                  explanation: "Absolute strength that never diminishes."),
        AllahName(id: 54, transliteration: "Al-Mateen", arabic: "الْمَتِينُ", meaning: "The Steadfast", alsoMeans: "The Steadfast, The Firm",
                  explanation: "Firm, unwavering. Consistency is a gift from the eternally consistent."),
        AllahName(id: 55, transliteration: "Al-Waliyy", arabic: "الْوَلِيُّ", meaning: "The Protecting Friend", alsoMeans: "The Protecting Friend, The Helper",
                  explanation: "The close ally of believers. More invested in your success than you are."),
        AllahName(id: 56, transliteration: "Al-Hameed", arabic: "الْحَمِيدُ", meaning: "The All-Praiseworthy", alsoMeans: "The Praised One, The Laudable",
                  explanation: "The most powerful thing you can say is praise of Him."),
        AllahName(id: 57, transliteration: "Al-Muhsi", arabic: "الْمُحْصِي", meaning: "The Accounter", alsoMeans: "The Counter of All, The Appraiser",
                  explanation: "He counts everything. Your effort matters. Every rep counts."),
        AllahName(id: 58, transliteration: "Al-Mubdi'", arabic: "الْمُبْدِئُ", meaning: "The Originator", alsoMeans: "The Initiator, The Beginner",
                  explanation: "He creates from nothing. If the idea is in your heart, originate it."),
        AllahName(id: 59, transliteration: "Al-Mu'id", arabic: "الْمُعِيدُ", meaning: "The Restorer", alsoMeans: "The Restorer, The Reproducer",
                  explanation: "Nothing is permanently lost. The dream that died can be resurrected."),
        AllahName(id: 60, transliteration: "Al-Muhyi", arabic: "الْمُحْيِي", meaning: "The Giver of Life", alsoMeans: "The Reviver, The Life-Giver",
                  explanation: "He makes dead things live again."),
        AllahName(id: 61, transliteration: "Al-Mumit", arabic: "الْمُمِيتُ", meaning: "The Bringer of Death", alsoMeans: "The Taker of Life, The Bringer of Death",
                  explanation: "Death strips illusions of permanence. Live with urgency."),
        AllahName(id: 62, transliteration: "Al-Hayy", arabic: "الْحَيُّ", meaning: "The Ever-Living", alsoMeans: "The Alive, The Living One",
                  explanation: "He will never die. You will. Build with purpose, not attachment."),
        AllahName(id: 63, transliteration: "Al-Qayyum", arabic: "الْقَيُّومُ", meaning: "The Self-Subsisting", alsoMeans: "The Self-Existing, The Eternal",
                  explanation: "You are not the sustainer. He is."),
        AllahName(id: 64, transliteration: "Al-Wajid", arabic: "الْوَاجِدُ", meaning: "The Finder", alsoMeans: "The Perceiver, The Finder",
                  explanation: "He finds the solution before you see the problem."),
        AllahName(id: 65, transliteration: "Al-Majid", arabic: "الْمَاجِدُ", meaning: "The Illustrious", alsoMeans: "The Glorious, The Most Noble",
                  explanation: "An illustrious life is measured in sincerity, not followers."),
        AllahName(id: 66, transliteration: "Al-Wahid", arabic: "الْوَاحِدُ", meaning: "The Unique", alsoMeans: "The Unique One, The Singular",
                  explanation: "Let my family reflect something rare and intentional."),
        AllahName(id: 67, transliteration: "Al-Ahad", arabic: "الْأَحَدُ", meaning: "The Indivisible", alsoMeans: "The Indivisible, The One and Only",
                  explanation: "Stop serving multiple gods. Serve the One."),
        AllahName(id: 68, transliteration: "As-Samad", arabic: "الصَّمَدُ", meaning: "The Self-Sufficient", alsoMeans: "The Eternal Refuge, The Self-Sufficient Master",
                  explanation: "Everything depends on Him. Turn to Him first."),
        AllahName(id: 69, transliteration: "Al-Qadir", arabic: "الْقَادِرُ", meaning: "The All-Powerful", alsoMeans: "The Omnipotent, The Capable",
                  explanation: "He created galaxies. Don't limit your du'a."),
        AllahName(id: 70, transliteration: "Al-Muqtadir", arabic: "الْمُقْتَدِرُ", meaning: "The All-Determiner", alsoMeans: "The All-Determining, The Empowered",
                  explanation: "The Determiner is not the algorithm."),
        AllahName(id: 71, transliteration: "Al-Muqaddim", arabic: "الْمُقَدِّمُ", meaning: "The Expediter", alsoMeans: "The One Who Brings Forward, The Expediter",
                  explanation: "He puts the right words in your mouth at the right moment."),
        AllahName(id: 72, transliteration: "Al-Mu'akhkhir", arabic: "الْمُؤَخِّرُ", meaning: "The Delayer", alsoMeans: "The One Who Delays, The Deferrer",
                  explanation: "Sometimes reflecting your own procrastination back at you."),
        AllahName(id: 73, transliteration: "Al-Awwal", arabic: "الْأَوَّلُ", meaning: "The First", alsoMeans: "The Beginning, The Eternal First",
                  explanation: "If health is the foundation, it must come first."),
        AllahName(id: 74, transliteration: "Al-Akhir", arabic: "الْآخِرُ", meaning: "The Last", alsoMeans: "The Eternal Last, The Final",
                  explanation: "The only thing that matters is how you arrive at the endpoint."),
        AllahName(id: 75, transliteration: "Adh-Dhahir", arabic: "الظَّاهِرُ", meaning: "The Manifest", alsoMeans: "The Evident, The Apparent",
                  explanation: "What is hidden will become manifest when He decides."),
        AllahName(id: 76, transliteration: "Al-Batin", arabic: "الْبَاطِنُ", meaning: "The Hidden", alsoMeans: "The Concealed, The Inner",
                  explanation: "He sees the hidden things inside you."),
        AllahName(id: 77, transliteration: "Al-Wali", arabic: "الْوَالِي", meaning: "The Patron", alsoMeans: "The Patron, The Governing Lord",
                  explanation: "For the one juggling everything alone — He manages what you cannot."),
        AllahName(id: 78, transliteration: "Al-Muta'ali", arabic: "الْمُتَعَالِي", meaning: "Supremely Exalted", alsoMeans: "The Supreme, The Most Exalted",
                  explanation: "Live above the things that pull you down."),
        AllahName(id: 79, transliteration: "Al-Barr", arabic: "الْبَرُّ", meaning: "Source of Goodness", alsoMeans: "The Righteous, The Doer of Good",
                  explanation: "When you want to be good — not just successful — you reflect Al-Barr."),
        AllahName(id: 80, transliteration: "At-Tawwab", arabic: "التَّوَّابُ", meaning: "Acceptor of Repentance", alsoMeans: "The Relenting, The Oft-Returning",
                  explanation: "He turns toward you before you turn toward Him."),
        AllahName(id: 81, transliteration: "Al-Muntaqim", arabic: "الْمُنْتَقِمُ", meaning: "The Avenger", alsoMeans: "The Avenger, The Requiter of Evil",
                  explanation: "He avenges with perfect justice. His courtroom cannot be vetoed."),
        AllahName(id: 82, transliteration: "Al-'Afuww", arabic: "الْعَفُوُّ", meaning: "The Pardoner", alsoMeans: "The Effacer, The Grantor of Pardon",
                  explanation: "He doesn't just forgive — He erases. He loves to pardon."),
        AllahName(id: 83, transliteration: "Ar-Ra'uf", arabic: "الرَّءُوفُ", meaning: "The Most Kind", alsoMeans: "The Clement, The Tender",
                  explanation: "Extreme gentleness. Active, relentless kindness."),
        AllahName(id: 84, transliteration: "Malik ul-Mulk", arabic: "مَالِكُ الْمُلْكِ", meaning: "Owner of Sovereignty", alsoMeans: "The Owner of All Sovereignty",
                  explanation: "He gives kingdom and takes it. The sovereignty is always borrowed."),
        AllahName(id: 85, transliteration: "Dhul Jalali wal Ikram", arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", meaning: "Lord of Majesty & Generosity", alsoMeans: "The Lord of Glory and Generosity",
                  explanation: "Both majesty and generosity. Commands respect and offers warmth."),
        AllahName(id: 86, transliteration: "Al-Muqsit", arabic: "الْمُقْسِطُ", meaning: "The Equitable", alsoMeans: "The Just, The Equitable One",
                  explanation: "On Judgment Day, every atom of injustice will be corrected."),
        AllahName(id: 87, transliteration: "Al-Jami'", arabic: "الْجَامِعُ", meaning: "The Gatherer", alsoMeans: "The Collector, The Uniter",
                  explanation: "He gathers hearts and families."),
        AllahName(id: 88, transliteration: "Al-Ghaniyy", arabic: "الْغَنِيُّ", meaning: "The Self-Sufficient", alsoMeans: "The Independent, The Self-Sufficient",
                  explanation: "Completely free of need yet He provides."),
        AllahName(id: 89, transliteration: "Al-Mughni", arabic: "الْمُغْنِي", meaning: "The Enricher", alsoMeans: "The Emancipator, The Enricher",
                  explanation: "He enriches in every dimension. True wealth is halal income plus inner contentment."),
        AllahName(id: 90, transliteration: "Al-Mani'", arabic: "الْمَانِعُ", meaning: "The Preventer", alsoMeans: "The Withholder, The Defender",
                  explanation: "Sometimes His prevention is His greatest mercy."),
        AllahName(id: 91, transliteration: "Ad-Darr", arabic: "الضَّارُّ", meaning: "The Afflictor", alsoMeans: "The Distresser, The Afflicter",
                  explanation: "He creates hardship with wisdom. The Ummah's suffering is not in vain."),
        AllahName(id: 92, transliteration: "An-Nafi'", arabic: "النَّافِعُ", meaning: "The Source of Good", alsoMeans: "The Benefiter, The Creator of Good",
                  explanation: "Every good thing that reaches you came from Him."),
        AllahName(id: 93, transliteration: "An-Nur", arabic: "النُّورُ", meaning: "The Light", alsoMeans: "The Divine Light, The Illuminator",
                  explanation: "He illuminates hearts, paths, and destinies."),
        AllahName(id: 94, transliteration: "Al-Hadi", arabic: "الْهَادِي", meaning: "The Guide", alsoMeans: "The Way-Shower, The Right Guide",
                  explanation: "He guides through revelation, signs, and hearts."),
        AllahName(id: 95, transliteration: "Al-Badi'", arabic: "الْبَدِيعُ", meaning: "The Incomparable", alsoMeans: "The Unprecedented, The Wonderful Originator",
                  explanation: "He creates without precedent."),
        AllahName(id: 96, transliteration: "Al-Baqi", arabic: "الْبَاقِي", meaning: "The Everlasting", alsoMeans: "The Permanent, The Eternal Survivor",
                  explanation: "Everything you build will vanish. Only what was done for His sake will last."),
        AllahName(id: 97, transliteration: "Al-Warith", arabic: "الْوَارِثُ", meaning: "The Inheritor", alsoMeans: "The Supreme Heir, The Inheritor of All",
                  explanation: "You are a steward, not an owner."),
        AllahName(id: 98, transliteration: "Ar-Rasheed", arabic: "الرَّشِيدُ", meaning: "The Right Guide", alsoMeans: "The Rightly-Guided, The Infallible Teacher",
                  explanation: "There is a right path. Walk it."),
        AllahName(id: 99, transliteration: "As-Sabur", arabic: "الصَّبُورُ", meaning: "The Most Patient", alsoMeans: "The Enduring, The Most Patient",
                  explanation: "The One who created time is never in a rush. Why are you?"),
    ]
}
